version: '3.5'

services:
  mongoservice:
    image: mongo
    container_name: mongoservice
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017
    logging:
      driver: "json-file"
      
  db:
    container_name: dbservice
    ports:
      - 5432:5432
    volumes:
    - ./service:/var/lib/postgresql
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=service
    image: postgres:latest
    logging:
      driver: "json-file"
    
  tcache:
    image: redis:latest
    container_name: tcache
    restart: on-failure
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass hellonadya

  auth:
    container_name: authenticate
    ports:
      - 7000:7000
    build: ./authenticate
    depends_on:
      - db
      - tcache
    restart: on-failure
    environment:
      - DB_PORT=5432
      - DB_HOST=dbservice
      - DB_NAME=service
      - DB_USER=user
      - DB_PASSWORD=root
      - REMOTE_PORT=7000
  forms:
    container_name: forms
    ports:
      - 8080:8080
    build: ./forms
    depends_on:
      - db
      - tcache
    restart: on-failure
    environment:
      - DB_PORT=5432
      - DB_HOST=dbservice
      - DB_NAME=service
      - DB_USER=user
      - DB_PASSWORD=root
      - REMOTE_PORT=8080
  messanger:
    container_name: messanger
    ports:
      - 9000:9000
    build: ./messanger
    depends_on:
      - mongoservice
    restart: on-failure
    environment:
      - MONGO_HOST=mongoservice
      - MONGO_PORT=27017
      - MONGO_USER=root
      - MONGO_PWD=root
      - REMOTE_PORT=9000